definitions:
  ID64:
    properties:
      id:
        type: integer
    type: object
  Permission:
    properties:
      method:
        type: string
      path:
        type: string
      uuid:
        type: string
    type: object
  Role:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      pages:
        $ref: '#/definitions/sharedutil.JsonObject'
      permissions:
        $ref: '#/definitions/sharedutil.JsonObject'
    type: object
  RoleCreate:
    properties:
      description:
        type: string
      name:
        type: string
      pages:
        $ref: '#/definitions/sharedutil.JsonObject'
      permissions:
        $ref: '#/definitions/sharedutil.JsonObject'
    type: object
  RolePage:
    properties:
      currentPage:
        type: integer
      data:
        items:
          $ref: '#/definitions/Role'
        type: array
      pageSize:
        type: integer
      total:
        type: integer
      totalPages:
        type: integer
    type: object
  sharedutil.JsonObject:
    additionalProperties: {}
    type: object
info:
  contact: {}
paths:
  /role:
    post:
      consumes:
      - application/json
      description: Create a new role
      operationId: create-role
      parameters:
      - description: role information
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/RoleCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Successful operation
          schema:
            $ref: '#/definitions/ID64'
        "400":
          description: Bad request
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create role
      tags:
      - role
  /role/{id}:
    get:
      consumes:
      - application/json
      description: GetContent role by ID
      operationId: get-role-by-id
      parameters:
      - description: role ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/Role'
        "400":
          description: Bad request
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: GetContent role by ID
      tags:
      - role
  /role/page:
    get:
      description: role-service-page
      parameters:
      - in: query
        name: description
        type: string
      - in: query
        name: name
        type: string
      - in: query
        name: organization_id
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Items per page
        in: query
        name: perpage
        type: integer
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/RolePage'
        "400":
          description: Bad request
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: role-service-page
      tags:
      - role
  /role/permissions:
    get:
      consumes:
      - application/json
      description: get-all-permissions
      operationId: get-all-permissions
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Items per page
        in: query
        name: perpage
        type: integer
      - description: Search term
        in: query
        name: search
        type: string
      - description: Without paginate
        in: query
        name: without_paginate
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: List of permissions
          schema:
            items:
              $ref: '#/definitions/Permission'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: get-all-permissions
      tags:
      - role
  /role/search:
    get:
      consumes:
      - application/json
      description: GetContent all role with pagination
      operationId: search-role
      parameters:
      - in: query
        name: description
        type: string
      - in: query
        name: name
        type: string
      - in: query
        name: organization_id
        type: integer
      - default: 20
        description: Limit the number of results
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            items:
              $ref: '#/definitions/Role'
            type: array
        "400":
          description: Bad request
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: GetContent all role with pagination
      tags:
      - role
swagger: "2.0"
