networks:
  stack:
    name: stack

services:
  db-platform-idoctor:
    container_name: db-platform-idoctor
    image: postgres:16-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /srv/platform_idoctor/docker/postgres/pgdata:/var/lib/postgresql/data
    networks:
      - stack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  platform-idoctor-redis-db:
    container_name: platform-idoctor-redis
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - /srv/platform_idoctor/docker/redis/data:/data
    networks:
      - stack

  platform-idoctor-app:
    container_name: platform-idoctor
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - CI_JOB_LOGIN=${CI_JOB_LOGIN}
        - CI_JOB_TOKEN=${CI_JOB_TOKEN}
        - HTTP_PORT=${HTTP_PORT}
    restart: always
    working_dir: "/app"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - /srv/platform_idoctor/docker/app/files:/app/files
    environment:
      - CI_JOB_LOGIN=${CI_JOB_LOGIN}
      - CI_JOB_TOKEN=${CI_JOB_TOKEN}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRED=${JWT_EXPIRED}
      - JWT_REFRESH_EXPIRED=${JWT_REFRESH_EXPIRED}
      
      - HTTP_PORT=${HTTP_PORT}
      - REDIS_ADDR=${REDIS_ADDR}
      
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
      - POSTGRES_TIME_ZONE=${POSTGRES_TIME_ZONE}
      
      - BOT_TOKEN=${BOT_TOKEN}
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.platform-idoctor-app.rule=Host(`api.idoctor.uz`)"
    #   - "traefik.http.routers.platform-idoctor-app.entrypoints=web"
    #   - "traefik.http.services.platform-idoctor-app.loadbalancer.server.port=80"
    #   - "traefik.docker.network=traefik-network"
    networks:
      - stack
    links:
      - db-platform-idoctor
      - platform-idoctor-redis-db
    depends_on:
      - db-platform-idoctor
      - platform-idoctor-redis-db
    command: "/app/main"

  platform_idoctor_bot:
    container_name: platform_idoctor_bot
    restart: always
    networks:
      - stack
    build:
      context: ./idoctor_bot
      dockerfile: ./Dockerfile
      args:
        - CI_JOB_LOGIN=${CI_JOB_LOGIN}
        - CI_JOB_TOKEN=${CI_JOB_TOKEN}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db-platform-idoctor
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
      - POSTGRES_TIME_ZONE=${POSTGRES_TIME_ZONE}

      - BOT_TOKEN=${BOT_TOKEN}
      - ADMINS=${ADMINS}
    volumes:
      - /srv/platform_idoctor/docker/app/files:/app/files
    depends_on:
      db-platform-idoctor:
        condition: service_healthy
    command: "/app/main"