networks:
  traefik-network:
    external: true
  stack:
    name: stack

services:
  db-inspector-mehnat:
    container_name: db-inspector-mehnat
    image: postgres:16-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /srv/inspector_mehnat/docker/postgres/pgdata:/var/lib/postgresql/data
    networks:
      - stack
      - traefik-network

  inspector-mehnat-redis-db:
    container_name: inspector-mehnat-redis
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - /srv/inspector_mehnat/docker/redis/data:/data
    networks:
      - stack

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    environment:
      - JWT_ENABLED=false # disable JWT for now (simpler testing)
    networks:
      - stack
      - traefik-network

  e-imzo-server:
    container_name: e-imzo-server
    build:
      context: ./e-imzo-server
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - E_IMZO_LISTEN_IP=${E_IMZO_LISTEN_IP}
      - E_IMZO_LISTEN_PORT=${E_IMZO_LISTEN_PORT}
      - E_IMZO_VPN_TLS_ENABLED=${E_IMZO_VPN_TLS_ENABLED}
      - E_IMZO_VPN_CONNECT_HOST=${E_IMZO_VPN_CONNECT_HOST}
      - E_IMZO_VPN_CONNECT_PORT=${E_IMZO_VPN_CONNECT_PORT}
      - E_IMZO_VPN_KEY_FILE_PATH=${E_IMZO_VPN_KEY_FILE_PATH}
      - E_IMZO_VPN_KEY_PASSWORD=${E_IMZO_VPN_KEY_PASSWORD}
      - E_IMZO_VPN_TRUSTSTORE_FILE_PATH=${E_IMZO_VPN_TRUSTSTORE_FILE_PATH}
      - E_IMZO_TSP_JKS_FILE_PATH=${E_IMZO_TSP_JKS_FILE_PATH}
    networks:
      - stack

  inspector-mehnat-app:
    container_name: inspector-mehnat
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - CI_JOB_LOGIN=${CI_JOB_LOGIN}
        - CI_JOB_TOKEN=${CI_JOB_TOKEN}
        - HTTP_PORT=${HTTP_PORT}
    restart: always
    working_dir: "/app"
    volumes:
      - /srv/inspector_mehnat/docker/app/files:/app/files
    environment:
      - CI_JOB_LOGIN=${CI_JOB_LOGIN}
      - CI_JOB_TOKEN=${CI_JOB_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - ONEID_CLIENT_SECRET=${ONEID_CLIENT_SECRET}
      - ONEID_CLIENT_ID=${ONEID_CLIENT_ID}
      - ONEID_CLIENT_REDIRECT_URL=${ONEID_CLIENT_REDIRECT_URL}
      - ONEID_DASHBOARD_REDIRECT_URL=${ONEID_DASHBOARD_REDIRECT_URL}
      - ONEID_BASE_URL=${ONEID_BASE_URL}
      - JWT_EXPIRED=${JWT_EXPIRED}
      - JWT_REFRESH_EXPIRED=${JWT_REFRESH_EXPIRED}
      - HTTP_PORT=${HTTP_PORT}
      - REDIS_ADDR=${REDIS_ADDR}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
      - POSTGRES_TIME_ZONE=${POSTGRES_TIME_ZONE}
      - GATEWAY_BASE_URL=${GATEWAY_BASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inspector-mehnat-app.rule=Host(`api.inspector.mehnat.sriss.uz`)"
      - "traefik.http.routers.inspector-mehnat-app.entrypoints=web"
      - "traefik.http.services.inspector-mehnat-app.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-network"
    networks:
      - traefik-network
      - stack
    links:
      - db-inspector-mehnat
      - inspector-mehnat-redis-db
      - e-imzo-server
    depends_on:
      - db-inspector-mehnat
      - inspector-mehnat-redis-db
      - e-imzo-server
    command: "/app/main"

  inspector_mehnat_bot:
    container_name: inspector_mehnat_bot
    restart: always
    networks:
      - stack
    build:
      context: ./dmi_bot
      dockerfile: ./Dockerfile
      args:
        - CI_JOB_LOGIN=${CI_JOB_LOGIN}
        - CI_JOB_TOKEN=${CI_JOB_TOKEN}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
      - POSTGRES_TIME_ZONE=${POSTGRES_TIME_ZONE}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMINS=${ADMINS}
    volumes:
      - /srv/inspector_mehnat/docker/app/files:/app/files
    command: "/app/main"
