name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker build
        env:
          CI_JOB_LOGIN:         x
          CI_JOB_TOKEN:         ${{ secrets.PAT_TOKEN }}
          JWT_SECRET:           ${{ secrets.DEV_JWT_SECRET }}
          BOT_TOKEN:            ${{ secrets.DEV_BOT_TOKEN }}
          POSTGRES_PASSWORD:    ${{ secrets.DEV_POSTGRES_PASSWORD }}
          JWT_EXPIRED:          ${{ vars.DEV_JWT_EXPIRED }}
          JWT_REFRESH_EXPIRED:  ${{ vars.DEV_JWT_REFRESH_EXPIRED }}
          HTTP_PORT:            ${{ vars.DEV_HTTP_PORT }}
          REDIS_ADDR:           ${{ vars.DEV_REDIS_ADDR }}
          POSTGRES_DB:          ${{ vars.DEV_POSTGRES_DB }}
          POSTGRES_HOST:        ${{ vars.DEV_POSTGRES_HOST }}
          POSTGRES_PORT:        ${{ vars.DEV_POSTGRES_PORT }}
          POSTGRES_USER:        ${{ vars.DEV_POSTGRES_USER }}
          POSTGRES_SSL_MODE:    ${{ vars.DEV_POSTGRES_SSL_MODE }}
          POSTGRES_TIME_ZONE:   ${{ vars.DEV_POSTGRES_TIME_ZONE }} 
          ADMINS:               ${{ vars.DEV_BOT_ADMINS }}
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up --build --force-recreate --remove-orphans -d

      - name: Wait for containers
        run: |
          sleep 5
      - name: List running containers
        run: |
          docker ps -a
