export const client = [
	"PAGE_EMPTY",
	"PAGE_FORBIDDEN",
	"PAGE_PROFILE",

	"ORDER_PAGE",
	"ORDER_VIEW",

	"ORDER_PART_PAGE",
	"ORDER_PART_VIEW",
];

export const master = [
	"PAGE_EMPTY",
	"PAGE_FORBIDDEN",
	"PAGE_PROFILE",

	"ORDER_CREATE",
	"ORDER_EDIT",
	"ORDER_PAGE",
	"ORDER_VIEW",

	"ORDER_PART_CREATE",
	"ORDER_PART_EDIT",
	"ORDER_PART_PAGE",
	"ORDER_PART_VIEW",
];

export const admin = [
	"404_PAGE",

	"DEVICE_CREATE",
	"DEVICE_EDIT",
	"DEVICE_PAGE",
	"DEVICE_VIEW",

	"LANGUAGE_CREATE",
	"LANGUAGE_EDIT",
	"LANGUAGE_PAGE",
	"LANGUAGE_VIEW",

	"ORDER_CREATE",
	"ORDER_EDIT",
	"ORDER_PAGE",
	"ORDER_VIEW",

	"ORDER_PART_CREATE",
	"ORDER_PART_EDIT",
	"ORDER_PART_PAGE",
	"ORDER_PART_VIEW",

	"PAGE_EMPTY",
	"PAGE_FORBIDDEN",
	"PAGE_PROFILE",

	"PAGE_ROLE",
	"CREATE_ROLE",
	"EDIT_ROLE",
	"ROLE_VIEW",

	"PART_CREATE",
	"PART_EDIT",
	"PART_PAGE",
	"PART_VIEW",

	"PROBLEM_CREATE",
	"PROBLEM_EDIT",
	"PROBLEM_PAGE",
	"PROBLEM_VIEW",

	"SUPPLIER_CREATE",
	"SUPPLIER_EDIT",
	"SUPPLIER_PAGE",
	"SUPPLIER_VIEW",

	"TRANSLATED_CONTENT",
	"TRANSLATED_CONTENT_VIEW",
	"TRANSLATE_CREATE",
	"TRANSLATE_DELETE",
	"TRANSLATE_UPDATE",

	"USER_CREATE",
	"USER_DELETE",
	"USER_EDIT",
	"USER_PAGE",
	"USER_VIEW",

	"STATISTICS_PAGE",
	"STATISTICS_MASTERS",
	"STATISTICS_ORDERS",
	"STATISTICS_PAYMENTS",
	"STATISTICS_REVENUE",
	"STATISTICS_TOP_PARTS",
];
